### ISSUE TITLE
Using of LinkedList

### ISSUE THREAD

**Issue by AleksTrue** [wumpz/java-diff-utils#12]
Hi!
You can see using LinkedList in many places and also using the method `list.get(i)`. In this case, to get n'th element we should iterate through n-1 items in the list. And a cycle `for (int i=0; ...` has n^2 complexity.

May be, such code should be replaced with `for (T item : list)` or LinkedList should be replaced with ArrayList. 

For example, in [DiffRowGenerator](https://github.com/wumpz/java-diff-utils/blob/5d5218ba30104ab90b0e2306a7b4e5c6347389c4/src/main/java/com/github/difflib/text/DiffRowGenerator.java#L263)
```
final List<Delta<String>> deltaList = patch.getDeltas();
        for (int i = 0; i < deltaList.size(); i++) {
            Delta<String> delta = deltaList.get(i);
```
and [patch#deltas](https://github.com/wumpz/java-diff-utils/blob/5d5218ba30104ab90b0e2306a7b4e5c6347389c4/src/main/java/com/github/difflib/patch/Patch.java#L40) is LinkedList.

We also can see `get(i)` in MyersDiff.java.

**Comment by wumpz** [comment]
Have to think about it. Array list has in  some cases memory problems. E.g resizing.

-------- Ursprüngliche Nachricht --------
Von: AleksTrue <notifications@github.com> 
Datum: 30.08.2017  11:00  (GMT+01:00) 
An: wumpz/java-diff-utils <java-diff-utils@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: [wumpz/java-diff-utils] Using of LinkedList (#12) 

Hi!

You can see using LinkedList in many places and also using the method list.get(i). In this case, to get n'th element we should iterate through n-1 items in the list. And a cycle for (int i=0; ... has n^2 complexity.
May be, such code should be replaced with for (T item : list) or LinkedList should be replaced with ArrayList.
For example, in DiffRowGenerator
final List<Delta<String>> deltaList = patch.getDeltas();
        for (int i = 0; i < deltaList.size(); i++) {
            Delta<String> delta = deltaList.get(i);

and patch#deltas is LinkedList.
We also can see get(i) in MyersDiff.java.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wumpz/java-diff-utils","title":"wumpz/java-diff-utils","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wumpz/java-diff-utils"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Using of LinkedList (#12)"}],"action":{"name":"View Issue","url":"https://github.com/wumpz/java-diff-utils/issues/12"}}}

**Comment by wumpz** [comment]
Looked into it. I will give it a try. After rewriting the whole to only "pointer" lists, this shouldnt be a problem anymore.

**Comment by wumpz** [comment]
I followed your tip and tried to prealocate the arraylists in the right size. Therefore a copy mem duplication should not occur.

**Comment by AleksTrue** [comment]
Many thanks!

**Comment by wumpz** [comment]
Did you have a massive performance impact? I had no time to make "large" diff tests.

**Comment by AleksTrue** [comment]
No. I just noticed this thing some time ago.
I wanted to fix this place by myself in near future and may be make performance tests, but suddenly found your project and that it's being developed.

**Comment by wumpz** [comment]
IT is kind of active. If you want to provide pull requests you are welcome.
